[package]
name = "rtools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.11.0"
flate2 = "1.0.24"
colored = "2.0.4"
termion = "2.0.3"
unicode-segmentation="1.10.1"


